# Generated by Django 3.2.16 on 2022-12-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('create_date', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('create_date', models.DateField()),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField()),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.todolist')),
            ],
        ),
    ]
