# Generated by Django 3.2.16 on 2022-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
